@apiUrl = http://localhost:3001/api

###

# @name getNotes
GET {{apiUrl}}/notes

###

# @name getNote
@noteId = 5d0b3e5e16ad69422268d75c
GET {{apiUrl}}/notes/{{noteId}}

###

# @name postNote
POST {{apiUrl}}/notes
Content-Type: application/json

{
  "content": "VSC REST-Client sopii hyvin REST-APIen testaamiseen",
  "important": true
}

###

# @name deleteNote
DELETE {{apiUrl}}/notes/{{noteId}}
